### ISSUE TITLE
create a 'units' section in the varTable file

### ISSUE THREAD

**Issue by dankelley** [dankelley/ocencdf#7]
That way, we can transform oce units to a string, and then map that string to a convention used in some group.  For example,
```R
library(oce)
data(ctd)
as.character(ctd[["temperatureUnit"]]$unit)
```
yields
```
degree * C
```
but some conventions might that as
```
degrees_Celsius
```
or perhaps
```
degrees on the Celsius (formerly known as the Centigrade) scale
```

I'm not 100% joking on that last name. Some systems have crazily long-winded names for things.

**Comment by dankelley** [comment]
The snap shows how it will work, for `argo` data. The code window shows conversion of the oce unit for temperature to the argo string for the same quantity.  (I'll make the code be more verbose so it will be easier for others to read and debug.)

<img width="787" alt="Screenshot 2023-05-30 at 6 26 21 AM" src="https://github.com/dankelley/ocencdf/assets/99469/451814f6-16bf-4f1f-b2b3-a462a10b3661">

**Comment by dankelley** [comment]
@avictor88 please note the new format of the yml files.  We will be saving unit conversions separately from variable-name conversions.  This format is not yet pushed to github; I'll do that once I recode things (within the hour).

**Comment by dankelley** [comment]
The following shows the new system (not yet stitched into the main codebase).

```r
library(ocencdf)
#> Loading required package: oce
#> Loading required package: gsw
data(ctd)
getVariableInfo(ctd, "temperature", "argo")
#> $name
#> [1] "TEMP"
#> 
#> $long_name
#> [1] "Sea temperature in-situ ITS-90 scale"
#> 
#> $standard_name
#> [1] "sea_water_temperature"
#> 
#> $FillValue
#> [1] 99999
#> 
#> $unit
#> [1] "degree_Celcius"
```

<sup>Created on 2023-05-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by dankelley** [comment]
I'm closing the issue because it (as defined by its title) has been accomplished.  (I pushed `inst/extdata/argo.yml` ... although the code does not yet incorporate it.)

**Comment by dankelley** [comment]
Hint: if you do as below (with your own file), you can check your work.  If you have a mistaken format (e.g. missing a ":") then an error will be reported.

```R
> y <- yaml::yaml.load_file("inst/extdata/argo.yml")
> str(y)
List of 3
 $ values   :List of 1
  ..$ missing_value: num 99999
 $ variables:List of 3
  ..$ temperature:List of 3
  .. ..$ name         : chr "TEMP"
  .. ..$ long_name    : chr "Sea temperature in-situ ITS-90 scale"
  .. ..$ standard_name: chr "sea_water_temperature"
  ..$ salinity   :List of 3
  .. ..$ name         : chr "PSAL"
  .. ..$ long_name    : chr "Practical Salinity"
  .. ..$ standard_name: chr "sea_water_salinity"
  ..$ pressure   :List of 3
  .. ..$ name         : chr "PRES"
  .. ..$ long_name    : chr "Sea water pressure, equals 0 at sea-level"
  .. ..$ standard_name: chr "sea_water_pressure"
 $ units    :List of 3
  ..$ degree * C :List of 1
  .. ..$ name: chr "degree_Celcius"
  ..$ dbar       :List of 1
  .. ..$ name: chr "decibar"
  ..$ mu * mol/kg:List of 1
  .. ..$ name: chr "micromole/kg"
```

**Comment by avictor88** [comment]
That's really handy, thank you!

**Comment by dankelley** [comment]
Here's another thing that might be helpful.  Try reading the code first, to see what you think it will do.  Then try it out, if you like.  (I might make a helper function in the package to do this.  Having things in a uniform format makes it a lot easier for folks to understand.)

```R
library(yaml)
y <- yaml.load_file("~/git/ocencdf/inst/extdata/argo.yml")
o <- order(names(y))
yy <- y[o]
for (name in names(yy)) {
    o <- order(names(yy[[name]]))
    yy[[name]] <- yy[[name]][o]
}
write_yaml(yy, "argo_test.yml")
```

**Comment by avictor88** [comment]
Is there a list of oce units that I could reference to do the unit conversions between argo and oce?

**Comment by avictor88** [comment]
Just saw your above comment, I'll try that out too.

**Comment by dankelley** [comment]
I think there must be at https://archimer.ifremer.fr/doc/00187/29825/

Note that the code will use a reasonable default, though.  I put in units for some common things.  I'm sure there are some chemistry things I haven't done yet.

I think we need one for oxygen percent saturation.  I have a thousand or so argo files on my computer and I might write a program to find the units in each.

**Comment by avictor88** [comment]
I've been trying to check if I'm writing to unit conversions in the right format using these lines that you used a little while back:
`a <- yaml::yaml.load_file("~/Desktop/03_paramNamesArgo.yml")
a$units[[as.character(ctd[["temperatureUnit"]]$unit)]]$name`

I've just been changing the variable from temperature to salinity, dissolved oxyen, conductivity, etc., but each time I try and run any variables other than temperature or pressure I get this error:

![Screen Shot 2023-05-30 at 12 23 20 PM](https://github.com/dankelley/ocencdf/assets/132913765/4cd2cb7f-6396-4cae-bbac-302a7921b08f)

[03_paramNamesArgo.pdf](https://github.com/dankelley/ocencdf/files/11601787/03_paramNamesArgo.pdf)

I attached the YAML file that I've been working on above. Since `conductivityCellTemperature` has the same units as `temperature` I didn't repeat these units in the list, but I'm not sure if that is right.

**Comment by dankelley** [comment]
Try doing
```R
library(oce)
data(ctd)
ctd[["dissolvedOxygenUnit"]]
```
where the third line is inside your code.  Notice that it is NULL.  That's because `ctd[["somethingUnit"]]` can only look up that unit if it is in the file.  It is not.  That file does not hold any oxygen data.  It only holds as below
```R
> names(ctd[["data"]])
[1] "scan"        "timeS"      
[3] "pressure"    "depth"      
[5] "temperature" "salinity"   
[7] "flag"  
```

At this stage, I think the best plan would be to put this aside until we can chat in person.  The thing is that the code will be changed a lot by tomorrow, and the new code will be simpler to understand.  Plus, I can teach you little things, like what I have at the start of this comment, without the time delay of writing up comments on GH.

**Comment by avictor88** [comment]
Okay, all of that sounds good I'm happy to go over it with you tomorrow.
